<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First_wpforms-161-field_0-last</name>
   <tag></tag>
   <elementGuidId>2d12c30c-18b4-45c6-87f4-0682e1d5ab6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wpforms-161-field_0-last</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wpforms-161-field_0-last']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Last&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94506b7d-d7d4-49a7-8b93-bdaf5e0319bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bec898f1-6dfc-4d50-94b9-92de004f51cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wpforms-161-field_0-last</value>
      <webElementGuid>4278a3e6-4ca2-4b7e-a059-e77d5190bf52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpforms-field-name-last wpforms-field-required</value>
      <webElementGuid>6965f803-85e0-4df1-aaa6-8ed66e7421d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wpforms[fields][0][last]</value>
      <webElementGuid>3e95dafe-2edc-490b-9bf9-09929499b551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpforms-161-field_0-last&quot;)</value>
      <webElementGuid>67e2431d-4832-424e-a5bf-1428cc133311</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wpforms-161-field_0-last']</value>
      <webElementGuid>6ba02700-8322-4beb-9da7-a4c0774194f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpforms-161-field_0-container']/div/div[2]/input</value>
      <webElementGuid>a046c25a-67fc-4dd7-bcb0-247672b62aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/input</value>
      <webElementGuid>d1ead69a-18bb-4a10-be78-cb1751da3f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'wpforms-161-field_0-last' and @name = 'wpforms[fields][0][last]']</value>
      <webElementGuid>20304bd7-de46-4791-9684-36218f9a8539</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
