<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__wpforms-161-field_0</name>
   <tag></tag>
   <elementGuidId>d2b9991a-44a9-4eee-a730-e6fbf1abc6ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wpforms-161-field_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wpforms-161-field_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;First&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0039e741-c7c9-4b7d-9ed9-dd30d5a3cb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>81587ac4-d3a4-4877-a022-7da59979240c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wpforms-161-field_0</value>
      <webElementGuid>7437b804-adfe-44d8-971e-ca86d532ec72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpforms-field-name-first wpforms-field-required</value>
      <webElementGuid>ea43fc37-6cbd-492d-b17a-94a4fbedfc29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wpforms[fields][0][first]</value>
      <webElementGuid>f0deee63-5069-488f-86ed-123eb34cdbe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpforms-161-field_0&quot;)</value>
      <webElementGuid>47f79a9e-9b9f-4233-81f7-6cd91ef7c6db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wpforms-161-field_0']</value>
      <webElementGuid>2f55fbdc-f01a-4812-838f-693f8d59e986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpforms-161-field_0-container']/div/div/input</value>
      <webElementGuid>31c1320d-a704-4fba-9533-45919e9e0074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>83c941e1-45ae-49b2-b57c-6ec5e28a8d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'wpforms-161-field_0' and @name = 'wpforms[fields][0][first]']</value>
      <webElementGuid>c0188fa3-e301-4b3a-b6ad-d420cc53aec5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
