<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_How do you plan to use the software_uHM_d8b6f7</name>
   <tag></tag>
   <elementGuidId>2d41d657-8192-47d6-9028-94e7e7c7659b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='i21']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.uHMk6b.fsHoPb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Web Testing&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cecb6e5b-17c2-4c05-a43a-d76e6baf7919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uHMk6b fsHoPb</value>
      <webElementGuid>c48e2356-2c85-461c-b237-7c33810a4042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i21&quot;)/div[@class=&quot;uHMk6b fsHoPb&quot;]</value>
      <webElementGuid>c603367c-7fb7-4f6f-a9dd-d3a0ae56682c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Frames - Web Automation Test/iframe</value>
      <webElementGuid>0731c422-d1e2-4c0d-ab63-eea01fb7574d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i21']/div[2]</value>
      <webElementGuid>83d9e2b2-7182-401e-9dee-240b0f312438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/div/div[2]</value>
      <webElementGuid>5e98bbaa-97d1-4334-8f93-838cd3215fdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
