<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Learn more_geS5n</name>
   <tag></tag>
   <elementGuidId>d45cc3f9-05e8-4b84-8c92-24aa713ca271</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='mG61Hd']/div[2]/div/div[2]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.geS5n</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Let's start with multiple choice.Hi, I am the UI.Vision IDEI am a humanOther:Cle&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>55b6c17b-9ea6-4ba7-bb2e-2388c31102c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jscontroller</name>
      <type>Main</type>
      <value>sWGJ4b</value>
      <webElementGuid>0193b8d0-ced8-4fa5-8e59-0bfe7db3f788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>EEvAHc:yfX9oc;</value>
      <webElementGuid>3c6b20e7-8388-4473-b0fe-7e1267738c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>WsjYwc</value>
      <webElementGuid>5f9bc679-1b79-4ccb-bf55-e062c09cec93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>geS5n</value>
      <webElementGuid>65a320e6-898b-4f85-a477-141876ab532c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Let's start with multiple choice.Hi, I am the UI.Vision IDEI am a humanOther:Clear selection</value>
      <webElementGuid>2eb449f8-7502-4346-adc7-70db121c4341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mG61Hd&quot;)/div[@class=&quot;RH5hzf RLS9Fe&quot;]/div[@class=&quot;lrKTG&quot;]/div[@class=&quot;o3Dpx&quot;]/div[@class=&quot;Qr7Oae&quot;]/div[1]/div[@class=&quot;geS5n&quot;]</value>
      <webElementGuid>08259a1d-aa19-4699-9b4d-e60af22b7707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Frames - Web Automation Test/iframe</value>
      <webElementGuid>2469b5da-cd75-432b-a3eb-5963d5f14eee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mG61Hd']/div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>f200d239-c3f5-4c21-914f-10cb6522d32e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/following::div[4]</value>
      <webElementGuid>bc7dbb79-be4c-435f-8895-49b8b168c0af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in to Google'])[1]/following::div[4]</value>
      <webElementGuid>d2148f9c-2fe3-4fe4-bcb4-ecffe2ebc57f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>ad96fa9c-4e8b-4285-897a-038c2db40119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Let&quot; , &quot;'&quot; , &quot;s start with multiple choice.Hi, I am the UI.Vision IDEI am a humanOther:Clear selection&quot;) or . = concat(&quot;Let&quot; , &quot;'&quot; , &quot;s start with multiple choice.Hi, I am the UI.Vision IDEI am a humanOther:Clear selection&quot;))]</value>
      <webElementGuid>43137eb6-b073-455d-ab8d-eb2c5848f1ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
