<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame</name>
   <tag></tag>
   <elementGuidId>1ff3fbfb-2fc4-4a3c-9514-565f73aea2b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>frame >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>19bc82ed-dc17-46aa-ab91-a8fb57b41ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>frame_1.html</value>
      <webElementGuid>a92edfcb-9d3a-4dc1-9f6d-237372f5c3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[1]</value>
      <webElementGuid>4159db11-45f8-4e54-9174-32f2959e120f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame</value>
      <webElementGuid>7de59aaf-8eee-4f60-86d9-65a934f9c2ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = 'frame_1.html']</value>
      <webElementGuid>aa8eaf25-9ee2-44f7-b8ae-691ac0ccacb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
