<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Get a FREE XPath cheat sheet by Signi_29ed3c</name>
   <tag></tag>
   <elementGuidId>024bab34-467c-4064-93fb-36165d3fd72e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form_first_name_7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form_first_name_7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Name *&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e899c2f3-736f-4cf4-9b26-ab17a37ca3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>950ded40-17a7-4367-b8b8-f2aefbf35c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>given-name</value>
      <webElementGuid>76336247-37bd-4957-a7db-7a7a0b675e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mailpoet_text</value>
      <webElementGuid>ba52d659-6ee6-482f-bc1a-a02e2267e683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_first_name_7</value>
      <webElementGuid>5aa23f60-e525-46fd-ab63-a4199d21bc33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[form_field_OTlkMTBlNjFjOGUwX2ZpcnN0X25hbWU=]</value>
      <webElementGuid>3d44bd8f-a7ea-4631-a9a5-ef9a2185eb77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>12fe3f88-4a3f-44d5-ac50-a2834f92fa62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>form_first_name</value>
      <webElementGuid>0456f4ed-ca48-4620-9890-dd39bdd6a785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name *</value>
      <webElementGuid>b759b81c-8791-4a7d-bf08-6c0671048974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Name *</value>
      <webElementGuid>ef0182a8-1d9f-4a09-a920-256a1b0fb94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-errors-container</name>
      <type>Main</type>
      <value>.mailpoet_error_13s6j</value>
      <webElementGuid>146c2398-86ec-45bd-9a27-fde30450fa36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-names</name>
      <type>Main</type>
      <value>[&quot;Please specify a valid name.&quot;,&quot;Addresses in names are not permitted, please add your name instead.&quot;]</value>
      <webElementGuid>d1ffb477-ea62-4f3d-9953-dde44cc45407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9e6e5edf-8804-4018-8687-5a92f7ff1863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eb2f3801-ebb8-4f9c-9b01-e2abba870d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required-message</name>
      <type>Main</type>
      <value>This field is required.</value>
      <webElementGuid>ae1a7b26-4b25-46c9-abdf-a16b1c82dc6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_first_name_7&quot;)</value>
      <webElementGuid>685707c5-3145-4454-8adc-45da15cfa2ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_first_name_7']</value>
      <webElementGuid>d5c02b7e-85f1-4346-9e94-68f33f9763d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mp_form_below_posts7']/form/div[2]/div/div/div/input</value>
      <webElementGuid>b269531e-ed2b-4f20-a9c2-184c0e30a6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>b742e456-4f0b-4a45-ac73-a093e403253a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'form_first_name_7' and @name = 'data[form_field_OTlkMTBlNjFjOGUwX2ZpcnN0X25hbWU=]' and @title = 'Name' and @placeholder = 'Name *']</value>
      <webElementGuid>36fee9e5-2d73-469d-b067-cdd995b62852</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
