<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Get a FREE XPath cheat sheet by Signi_7b26f4</name>
   <tag></tag>
   <elementGuidId>0c1fe1fd-b424-4693-ad29-aaa906a210d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.mailpoet_submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Get XPath cheat sheet']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Get XPath cheat sheet&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec2cb784-746e-45c3-aeff-b5dc85e89169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>82800748-651d-456a-8bb1-9d045df1f604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mailpoet_submit</value>
      <webElementGuid>8046f1c5-292e-48f7-b917-a9a1d0be5478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Get XPath cheat sheet</value>
      <webElementGuid>2581bc10-0572-4b51-9ea2-fa732811cc51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>subscribe-submit-button</value>
      <webElementGuid>e2ec7eba-3a00-4718-8995-c9ea5c514bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mp_form_below_posts7&quot;)/form[@class=&quot;mailpoet_form mailpoet_form_form mailpoet_form_below_posts&quot;]/div[@class=&quot;mailpoet_paragraph&quot;]/input[@class=&quot;mailpoet_submit&quot;]</value>
      <webElementGuid>877d19d6-8db0-4bea-9c87-74d791d605c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Get XPath cheat sheet']</value>
      <webElementGuid>a56e3a5f-3b6e-4657-a4c2-22248eea59b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mp_form_below_posts7']/form/div[3]/input</value>
      <webElementGuid>609f1c09-be44-4d52-9c55-82c45e41526f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>b6fba82f-ecba-4850-8915-aa2df5e27aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>aa938468-a715-4a87-b6ad-da4dab035a04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
