<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_privacy policy_mailpoet_form_close_icon</name>
   <tag></tag>
   <elementGuidId>08f7349c-7949-443e-8821-3926557cc9ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.mailpoet_form_close_icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='image']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Close&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5f628e0-b841-4581-b0bd-b04b75e49963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>bd34faf3-6b15-4429-8e07-0bd1d1a4bca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mailpoet_form_close_icon</value>
      <webElementGuid>b959b912-5126-4116-8dff-35f8a727d781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>e009cae7-cce2-4a41-a8c1-528301e54efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://practicetestautomation.com/wp-content/plugins/mailpoet/assets/img/form_close_icon/square_black.svg</value>
      <webElementGuid>61b67a08-f85a-4134-bc80-7ed84fe4d545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mp_form_slide_in8&quot;)/input[@class=&quot;mailpoet_form_close_icon&quot;]</value>
      <webElementGuid>5b28998c-4842-411e-ba2b-9708f165e361</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='image']</value>
      <webElementGuid>e535bcf6-eb6a-4859-8ae5-42c854bada20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mp_form_slide_in8']/input</value>
      <webElementGuid>4d59efb1-574a-46a2-b238-ae88a87385e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/input</value>
      <webElementGuid>9f1bc7f9-6648-4a6a-858c-9e3ba01ba3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @alt = 'Close' and @src = 'https://practicetestautomation.com/wp-content/plugins/mailpoet/assets/img/form_close_icon/square_black.svg']</value>
      <webElementGuid>061dea24-47f9-4334-96a2-d91662a675bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
